name: This is resuable-workflows


on:
  push:
    branches: ["main", "2*"]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:

  Run_Post_Processing_Job:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Write the purpose
        run: |
          echo "Running Run_Post_Processing_Job"

  Run_Validate_Job:
    needs : Run_Post_Processing_Job
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Write the purpose
        run: |
          echo "Run_Validate_Job"
          #if [[ ${github.ref_name} ~= "refs/heads" ]]
          echo ${{ github.ref_name }}