name: This is resuable-workflows


on:
  push:
    branches: ["main", "2*"]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:

  Run_Post_Processing_Job:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Run Post Processing Task
        run: |
          echo "Running Run_Post_Processing_Job"
          echo ${{ github.ref_name }} 
          if [[ ${{ github.ref_name }} ~= .*"loc_staging".* ]]; then
            echo "Running Preprocessing"
          else
            echo "Not Running Preprocessing"
          fi


  Run_Validate_Job:
    needs : Run_Post_Processing_Job
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Run Yarn Validate Task
        run: |
          echo "Run_Validate_Job"
          